---
halyard:
  spinnakerVersion: ${spinnaker_app_version}
  image:
    repository: ${registry}/releng/halyard
    tag: ${halyard_image_version}

dockerRegistries:
- name: harbor
  address: ${registry}
  username: ${user}
  password: ${password}

kubeConfig:
  enabled: ${upload_kubeconfig}
  secretName: spinnaker-kubeconfig
  secretKey: config
  contexts: ${spinnakker_target_contexts}
  deploymentContext: ${spinnaker_deployment_context}

ingress:
  enabled: true
  host: spinnaker.${env_domain}
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  tls:
  - secretName: nginx-ingress-tls
    hosts:
    - spinnaker.${env_domain}

ingressGate:
  enabled: false
  host: spin-gate.${env_domain}
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  tls:
  - secretName: nginx-ingress-tls
    hosts:
    - spin-gate.${env_domain}

redis:
  external:
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}

minio:
  enabled: false

s3:
  enabled: true
  endpoint: "http://${minio_host}:${minio_port}"
  accessKey: "${minio_access_key}"
  secretKey: "${minio_secret_key}"
  bucket: spinnaker
