---
controller:
  image:
    repository: ${registry}/releng/nginx-ingress-controller
    tag: ${nginx_ingress_controller_version}
  
  extraArgs:
    default-ssl-certificate: "${environment}/nginx-ingress-tls"

defaultBackend:
  image:
    repository: ${registry}/releng/defaultbackend
    tag: ${defaultbackend_version}
