  apiVersion: v1
  kind: Secret
  metadata:
    name: nginx-ingress-tls
    namespace: ${environment}
  data:
    tls.crt: ${nginx_ingress_tls_cert}
    tls.key: ${nginx_ingress_tls_key}
  type: kubernetes.io/tls